env: CartPole-v1
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 1000
freqSave: 1000
freqTest: 100
freqVerbose: 100
fromFile: null
gamma: 0.99
lr: 0.01
maxLengthTest: 500
maxLengthTrain: 500
mode: MC
nbEpisodes: 20000
nbTest: 1
seed: 5
tau: 0.99
