decay: 0.999
env: LunarLander-v2
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 1000
freqSave: 1000
freqTest: 10
freqVerbose: 10
fromFile: null
gamma: 0.99
lr: 0.02
maxLengthTest: 200
maxLengthTrain: 600
mode: MC
nbEpisodes: 1000000
nbTest: 1
seed: 5
tau: 0.99
