batchSize: 100
decay: 0.99999
env: CartPole-v1
explo: 0.1
exploMode: 0
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 1
freqSave: 1000
freqTest: 100
freqUpdateQ: 1000
freqVerbose: 10
fromFile: null
gamma: 0.999
hiddenSize: 200
learningRate: 0.0003
maxLengthTest: 500
maxLengthTrain: 100
memSize: 10000
nbEpisodes: 100000
nbTest: 1
seed: 5
