env: LunarLander-v2
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 200
nbTest: 100                                                                  # Optimisation de la politique tous les freqOptim evenements
fromFile: null
explo: 0.1
decay: 0.999
lr: 0.003
nbEpisodes: 10000
freqVerbose: 100
maxLengthTest: 300                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 300    
batch_size: 100
expert_data_path: './expert.pkl'