decay: 0.99999
env: CartPole-v1
explo: 0.1
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 10
freqSave: 1000
freqTarget: 100
freqTest: 100
freqVerbose: 100
fromFile: null
gamma: 0.99
lr_policy: 0.003
lr_value: 0.003
maxLengthTest: 500
maxLengthTrain: 300
nbEpisodes: 1000000
nbTest: 1
seed: 5
