env: CartPole-v1
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 40
freqSave: 1000
freqTest: 100
freqVerbose: 100
fromFile: null
gamma: 0.99
lr: 0.001
maxLengthTest: 500
maxLengthTrain: 300
mode: MC
nbEpisodes: 5000
nbTest: 1
seed: 5
tau: 0.95
