env: LunarLander-v2
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 100
nbTest: 1
freqVerbose: 10
freqOptim: 1                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 1000000

maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 100                                                                   # Longueur maxi des trajectoires en Train

fromFile: null                                                                        # si pas null, chargement du modèle a partir de ce fichier
exploMode: 0                                                                          # Mode d'exploration. 0 = epsilon-greedy (les autres a regarder je sais plus)
explo: 0.1                                                                            # coefficient d'exploration initial
decay: 0.99999                                                                          # a la fin de chaque trajectoire, le coefficient d'explo est multiplié par ce facteur
gamma: 0.999                                                                           # Facteur de discount
learningRate: 0.0003                                                                   # Pas d'apprentissage
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 100                                                                   # Longueur maxi des trajectoires en Train

hiddenSize: 200
memSize: 10000
batchSize: 1
freqUpdateQ: 1000